config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout"}

  get 'persons/profile'

  resources :users

  resources :sessions

 
  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  devise_scope :user do 
    root to: 'static_pages#home'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  resources :alcohol_drugs

  resources :drugs

  resources :alcohols

end

app/models/drug.rb
class Drug < ActiveRecord::Base
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :set_drug, only: [:show, :edit, :update, :destroy]

  # GET /drugs
  # GET /drugs.json
  def index
    @drugs = Drug.all
  end

  # GET /drugs/1
  # GET /drugs/1.json
  def show
  end

  # GET /drugs/new
  def new
    @drug = Drug.new
  end

  # GET /drugs/1/edit
  def edit
  end

  # POST /drugs
  # POST /drugs.json
  def create
    @drug = Drug.new(drug_params)

    respond_to do |format|
      if @drug.save
        format.html { redirect_to @drug, notice: 'Drug was successfully created.' }
        format.json { render :show, status: :created, location: @drug }
      else
        format.html { render :new }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drugs/1
  # PATCH/PUT /drugs/1.json
  def update
    respond_to do |format|
      if @drug.update(drug_params)
        format.html { redirect_to @drug, notice: 'Drug was successfully updated.' }
        format.json { render :show, status: :ok, location: @drug }
      else
        format.html { render :edit }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drugs/1
  # DELETE /drugs/1.json
  def destroy
    @drug.destroy
    respond_to do |format|
      format.html { redirect_to drugs_url, notice: 'Drug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drug
      @drug = Drug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drug_params
      params.require(:drug).permit(:addicted, :drug_type, :drugs_period, :previous_treatment)
    end
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/views/drugs/_form.html.erb
<%= form_for(@drug) do |f| %>
  <% if @drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drug.errors.count, "error") %> prohibited this drug from being saved:</h2>

      <ul>
      <% @drug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :addicted %><br>
    <%= f.number_field :addicted %>
  </div>
  <div class="field">
    <%= f.label :drug_type %><br>
    <%= f.text_field :drug_type %>
  </div>
  <div class="field">
    <%= f.label :drugs_period %><br>
    <%= f.number_field :drugs_period %>
  </div>
  <div class="field">
    <%= f.label :previous_treatment %><br>
    <%= f.text_area :previous_treatment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drugs/edit.html.erb
<h1>Editing Drug</h1>

<%= render 'form' %>

<%= link_to 'Show', @drug %> |
<%= link_to 'Back', drugs_path %>

app/views/drugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Drugs</h1>

<table>
  <thead>
    <tr>
      <th>Addicted</th>
      <th>Drug type</th>
      <th>Drugs period</th>
      <th>Previous treatment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drugs.each do |drug| %>
      <tr>
        <td><%= drug.addicted %></td>
        <td><%= drug.drug_type %></td>
        <td><%= drug.drugs_period %></td>
        <td><%= drug.previous_treatment %></td>
        <td><%= link_to 'Show', drug %></td>
        <td><%= link_to 'Edit', edit_drug_path(drug) %></td>
        <td><%= link_to 'Destroy', drug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drug', new_drug_path %>

app/views/drugs/new.html.erb
<h1>New Drug</h1>

<%= render 'form' %>

<%= link_to 'Back', drugs_path %>

app/views/drugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Addicted:</strong>
  <%= @drug.addicted %>
</p>

<p>
  <strong>Drug type:</strong>
  <%= @drug.drug_type %>
</p>

<p>
  <strong>Drugs period:</strong>
  <%= @drug.drugs_period %>
</p>

<p>
  <strong>Previous treatment:</strong>
  <%= @drug.previous_treatment %>
</p>

<%= link_to 'Edit', edit_drug_path(@drug) %> |
<%= link_to 'Back', drugs_path %>