config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout"}

  get 'persons/profile'

  resources :users

  resources :sessions

 
  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  devise_scope :user do 
    root to: 'static_pages#home'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  resources :alcohol_drugs

  resources :drugs

  resources :alcohols

end

app/models/alcohol_drug.rb
class AlcoholDrug < ActiveRecord::Base
end

app/controllers/alcohol_drugs_controller.rb
class AlcoholDrugsController < ApplicationController
  before_filter :auth_user

  def auth_user
    redirect_to new_user_registration_url unless user_signed_in?
  end

  before_action :set_alcohol_drug, only: [:show]

  # GET /alcohol_drugs
  # GET /alcohol_drugs.json
  def index
    @alcohol_drugs = AlcoholDrug.all
  end

  # GET /alcohol_drugs/1
  # GET /alcohol_drugs/1.json
  def show
  	flash[:notice] = 'Successfully added'
  	redirect_to url_for(:controller => :static_pages, :action => :home)
  end

  # GET /alcohol_drugs/new
  def new
    @alcohol_drug = AlcoholDrug.new
  end

  # GET /alcohol_drugs/1/edit
  def edit
  end

  # POST /alcohol_drugs
  # POST /alcohol_drugs.json
  def create
    @alcohol_drug = AlcoholDrug.new(alcohol_drug_params)

    respond_to do |format|
      if @alcohol_drug.save
        format.html { redirect_to @alcohol_drug, notice: 'Alcohol drug was successfully created.' }
        format.json { render :show, status: :created, location: @alcohol_drug }
      else
        format.html { render :new }
        format.json { render json: @alcohol_drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alcohol_drugs/1
  # PATCH/PUT /alcohol_drugs/1.json
  def update
    respond_to do |format|
      if @alcohol_drug.update(alcohol_drug_params)
        format.html { redirect_to @alcohol_drug, notice: 'Alcohol drug was successfully updated.' }
        format.json { render :show, status: :ok, location: @alcohol_drug }
      else
        format.html { render :edit }
        format.json { render json: @alcohol_drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alcohol_drugs/1
  # DELETE /alcohol_drugs/1.json
  def destroy
    @alcohol_drug.destroy
    respond_to do |format|
      format.html { redirect_to alcohol_drugs_url, notice: 'Alcohol drug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alcohol_drug
      @alcohol_drug = AlcoholDrug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alcohol_drug_params
      params.require(:alcohol_drug).permit(:alcohol_addicted, :drugs_adicted, :alcohol_type, :drugs_type, :alcohol_period, :drugs_period, :previous_treatment)
    end
end

app/helpers/alcohol_drugs_helper.rb
module AlcoholDrugsHelper
end

app/views/alcohol_drugs/_form.html.erb
<%= form_for(@alcohol_drug) do |f| %>
  <% if @alcohol_drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alcohol_drug.errors.count, "error") %> prohibited this alcohol_drug from being saved:</h2>

      <ul>
      <% @alcohol_drug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alcohol_addicted %><br>
    <%= f.number_field :alcohol_addicted %>
  </div>
  <div class="field">
    <%= f.label :drugs_adicted %><br>
    <%= f.number_field :drugs_adicted %>
  </div>
  <div class="field">
    <%= f.label :alcohol_type %><br>
    <%= f.text_field :alcohol_type %>
  </div>
  <div class="field">
    <%= f.label :drugs_type %><br>
    <%= f.text_field :drugs_type %>
  </div>
  <div class="field">
    <%= f.label :alcohol_period %><br>
    <%= f.number_field :alcohol_period %>
  </div>
  <div class="field">
    <%= f.label :drugs_period %><br>
    <%= f.number_field :drugs_period %>
  </div>
  <div class="field">
    <%= f.label :previous_treatment %><br>
    <%= f.text_area :previous_treatment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alcohol_drugs/edit.html.erb
<h1>Editing Alcohol Drug</h1>

<%= render 'form' %>

<%= link_to 'Show', @alcohol_drug %> |
<%= link_to 'Back', alcohol_drugs_path %>

app/views/alcohol_drugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alcohol Drugs</h1>

<table>
  <thead>
    <tr>
      <th>Alcohol addicted</th>
      <th>Drugs adicted</th>
      <th>Alcohol type</th>
      <th>Drugs type</th>
      <th>Alcohol period</th>
      <th>Drugs period</th>
      <th>Previous treatment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alcohol_drugs.each do |alcohol_drug| %>
      <tr>
        <td><%= alcohol_drug.alcohol_addicted %></td>
        <td><%= alcohol_drug.drugs_adicted %></td>
        <td><%= alcohol_drug.alcohol_type %></td>
        <td><%= alcohol_drug.drugs_type %></td>
        <td><%= alcohol_drug.alcohol_period %></td>
        <td><%= alcohol_drug.drugs_period %></td>
        <td><%= alcohol_drug.previous_treatment %></td>
        <td><%= link_to 'Show', alcohol_drug %></td>
        <td><%= link_to 'Edit', edit_alcohol_drug_path(alcohol_drug) %></td>
        <td><%= link_to 'Destroy', alcohol_drug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alcohol drug', new_alcohol_drug_path %>

app/views/alcohol_drugs/new.html.erb
<h1>New Alcohol Drug</h1>

<%= render 'form' %>

<%= link_to 'Back', alcohol_drugs_path %>

app/views/alcohol_drugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alcohol addicted:</strong>
  <%= @alcohol_drug.alcohol_addicted %>
</p>

<p>
  <strong>Drugs adicted:</strong>
  <%= @alcohol_drug.drugs_adicted %>
</p>

<p>
  <strong>Alcohol type:</strong>
  <%= @alcohol_drug.alcohol_type %>
</p>

<p>
  <strong>Drugs type:</strong>
  <%= @alcohol_drug.drugs_type %>
</p>

<p>
  <strong>Alcohol period:</strong>
  <%= @alcohol_drug.alcohol_period %>
</p>

<p>
  <strong>Drugs period:</strong>
  <%= @alcohol_drug.drugs_period %>
</p>

<p>
  <strong>Previous treatment:</strong>
  <%= @alcohol_drug.previous_treatment %>
</p>

<%= link_to 'Edit', edit_alcohol_drug_path(@alcohol_drug) %> |
<%= link_to 'Back', alcohol_drugs_path %>