config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout"}

  get 'persons/profile'

  resources :users

  resources :sessions

 
  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  devise_scope :user do 
    root to: 'static_pages#home'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  resources :alcohol_drugs

  resources :drugs

  resources :alcohols

end

app/models/alcohol.rb
class Alcohol < ActiveRecord::Base
end

app/controllers/alcohols_controller.rb
class AlcoholsController < ApplicationController
  before_action :set_alcohol, only: [:show, :edit, :update, :destroy]

  # GET /alcohols
  # GET /alcohols.json
  def index
    @alcohols = Alcohol.all
  end

  # GET /alcohols/1
  # GET /alcohols/1.json
  def show
  end

  # GET /alcohols/new
  def new
    @alcohol = Alcohol.new
  end

  # GET /alcohols/1/edit
  def edit
  end

  # POST /alcohols
  # POST /alcohols.json
  def create
    @alcohol = Alcohol.new(alcohol_params)

    respond_to do |format|
      if @alcohol.save
        format.html { redirect_to @alcohol, notice: 'Alcohol was successfully created.' }
        format.json { render :show, status: :created, location: @alcohol }
      else
        format.html { render :new }
        format.json { render json: @alcohol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alcohols/1
  # PATCH/PUT /alcohols/1.json
  def update
    respond_to do |format|
      if @alcohol.update(alcohol_params)
        format.html { redirect_to @alcohol, notice: 'Alcohol was successfully updated.' }
        format.json { render :show, status: :ok, location: @alcohol }
      else
        format.html { render :edit }
        format.json { render json: @alcohol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alcohols/1
  # DELETE /alcohols/1.json
  def destroy
    @alcohol.destroy
    respond_to do |format|
      format.html { redirect_to alcohols_url, notice: 'Alcohol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alcohol
      @alcohol = Alcohol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alcohol_params
      params.require(:alcohol).permit(:addicted, :type, :drinking_period, :previous_treatment)
    end
end

app/helpers/alcohols_helper.rb
module AlcoholsHelper
end

app/views/alcohols/_form.html.erb
<%= form_for(@alcohol) do |f| %>
  <% if @alcohol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alcohol.errors.count, "error") %> prohibited this alcohol from being saved:</h2>

      <ul>
      <% @alcohol.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :addicted %><br>
    <%= f.number_field :addicted %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :drinking_period %><br>
    <%= f.number_field :drinking_period %>
  </div>
  <div class="field">
    <%= f.label :previous_treatment %><br>
    <%= f.text_area :previous_treatment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alcohols/edit.html.erb
<h1>Editing Alcohol</h1>

<%= render 'form' %>

<%= link_to 'Show', @alcohol %> |
<%= link_to 'Back', alcohols_path %>

app/views/alcohols/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alcohols</h1>

<table>
  <thead>
    <tr>
      <th>Addicted</th>
      <th>Type</th>
      <th>Drinking period</th>
      <th>Previous treatment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alcohols.each do |alcohol| %>
      <tr>
        <td><%= alcohol.addicted %></td>
        <td><%= alcohol.type %></td>
        <td><%= alcohol.drinking_period %></td>
        <td><%= alcohol.previous_treatment %></td>
        <td><%= link_to 'Show', alcohol %></td>
        <td><%= link_to 'Edit', edit_alcohol_path(alcohol) %></td>
        <td><%= link_to 'Destroy', alcohol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alcohol', new_alcohol_path %>

app/views/alcohols/new.html.erb
<h1>New Alcohol</h1>

<%= render 'form' %>

<%= link_to 'Back', alcohols_path %>

app/views/alcohols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Addicted:</strong>
  <%= @alcohol.addicted %>
</p>

<p>
  <strong>Type:</strong>
  <%= @alcohol.type %>
</p>

<p>
  <strong>Drinking period:</strong>
  <%= @alcohol.drinking_period %>
</p>

<p>
  <strong>Previous treatment:</strong>
  <%= @alcohol.previous_treatment %>
</p>

<%= link_to 'Edit', edit_alcohol_path(@alcohol) %> |
<%= link_to 'Back', alcohols_path %>